name: Build & Deploy to AKS with Existing wizexercise.txt

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: repo
      
      - name: Verify repo contents
        run: |
          echo "Contents of repo root:"a
          ls -R repo
          echo "Checking Dockerfile for wizexercise.txt copy:"
          grep -Hn "COPY wizexercise.txt" repo/Dockerfile || true

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
