name: Build & Deploy to AKS with Existing wizexercise.txt

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/tasky:latest
          docker build \
            --file repo/Dockerfile \
            --tag $IMAGE \
            repo

      - name: Push Docker image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/tasky:latest
          docker push $IMAGE

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra code
        uses: actions/checkout@v3
        with:
          path: infra

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v2
        with:
          resource-group: tf-wiz-test-rg
          cluster-name: tf-wiz-aks

      - name: Deploy to AKS
        run: |
          export KUBECONFIG=~/.kube/config
          kubectl set image deployment/tasky \
            tasky=${{ secrets.ACR_LOGIN_SERVER }}/tasky:latest
          kubectl rollout status deployment/tasky --timeout=120s
