name: CI/CD Demo via ACR Tasks

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
      ACR_NAME:              tfwizacr17a02a
      RESOURCE_GROUP:        tf-wiz-test-rg
      AKS_NAME:              tf-wiz-aks

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        run: |
          az login --service-principal \
            -u $AZURE_CLIENT_ID \
            -p $AZURE_CLIENT_SECRET \
            --tenant $AZURE_TENANT_ID
          az account set --subscription $AZURE_SUBSCRIPTION_ID

      - name: Build & push via ACR Tasks
        run: |
          az acr build \
            --registry $ACR_NAME \
            --image tasky:with-txt \
            --file Dockerfile \
            .

      - name: Get AKS creds
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $AKS_NAME \
            --overwrite-existing

      - name: Roll out deployment
        run: |
          kubectl set image deployment/tasky \
            tasky=$ACR_NAME.azurecr.io/tasky:with-txt \
            --record
          kubectl rollout status deployment/tasky --timeout=120s
